/**
 * PM2 Ecosystem Configuration
 *
 * This file instructs PM2 to read environment variables from .env file
 * or from the shell environment.
 *
 * Usage:
 *   # First, source the environment (generates .env file)
 *   source .envrc
 *
 *   # Then start with PM2
 *   pm2 start ecosystem.config.js
 *
 *   # Or for production
 *   pm2 start ecosystem.config.js --env production
 */
const path = require('path');

module.exports = {
  apps: [{
    name: 'kedge-api-server',
    script: 'dist/packages/apps/api-server/main.js',
    cwd: __dirname,
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G',

    // Load environment variables from .env file
    // The .env file is generated by .envrc when you run `source .envrc`
    node_args: '-r dotenv/config',
    env_file: '.env',

    // Default environment
    env: {
      NODE_ENV: 'development',
    },

    // Production environment
    env_production: {
      NODE_ENV: 'production',
      LOG_LEVEL: 'info',
      ENABLE_DEBUG_INFO: 'false',
    }
  }]
};
